### ISSUE TITLE
COM voltage on Somfy IO Remote

### ISSUE THREAD

**Issue by Aviatorpaal** [robvdw2/somfy_situo5_io_esp32#1]
Thanks for doing a great job documenting your findings! I am planning to do the same and integrate it with Home Assistant.

However, I have a slightly different board than you, the Izymo Transmitter for IO: [https://www.somfy.me/en-gc/products/1822628/izymo-transmitter-io](url)

When I measure between the COM wire (ground?) and either S1 (down) or S2 (up) I measure 1.5V. Do you think it's safe connecting these to my ESP32 GPIO pins that have a 3V potential? Should I use a resistor or diode for this project?

**Comment by robvdw2** [comment]
The safest way to avoid the risk of damaging the transmitter board is probably to use a couple of simple optocouplers like the PC817.

**Comment by Aviatorpaal** [comment]
Thanks for the advice! Will do.
